x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo
  - D:/CODE/vedio-library/251208-蜡笔小新-总合集:/materials:ro
  - D:/CODE/vedio-library/251208-蜡笔小新-总合集/_ai_generated:/materials/_ai_generated

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-webui"
    ports:
      - "127.0.0.1:8700:8700"
    command: [ "streamlit", "run", "./webui/Main.py","--server.port=8700","--browser.serverAddress=127.0.0.1","--server.enableCORS=True","--browser.gatherUsageStats=False","--server.showEmailPrompt=False" ]
    volumes: *common-volumes
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-api"
    ports:
      - "127.0.0.1:8080:8080"
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    restart: always
